@task1_framework1_HostAddress = http://localhost:54255

POST http://localhost:54255/api/items
Content-Type: application/json

{
  "name": "Programming in C#",
  "price": 69.99
}

### Попытка создать предмет без имени, должно кинуть 400
POST http://localhost:54255/api/items
Content-Type: application/json

{
  "name": "",
  "price": 10
}

### Попытка создать предмет с отрицательной ценой, должно кинуть 400
POST http://localhost:54255/api/items
Content-Type: application/json

{
  "name": "Valid Name",
  "price": -5
}

### Получить все предметы, всегда кидает 200
GET http://localhost:54255/api/items

### Получить какой-нибудь предмет по uuid (надо вместо {id} вставить существующий uuid)
GET http://localhost:54255/api/items/{91394696-a8a2-4ed5-a0f3-a0bd0639cddc}

### Получить предметы с сортировкой по цене по возрастанию
GET http://localhost:54255/api/items/asc

### Получить предметы с сортировкой по цене по убыванию
GET http://localhost:54255/api/items/desc